# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  awakened-poe-trade = {
    pname = "awakened-poe-trade";
    version = "3.28.103";
    src = fetchurl {
      url = "https://github.com/SnosMe/awakened-poe-trade/releases/download/v3.28.103/Awakened-PoE-Trade-3.28.103-universal.dmg";
      sha256 = "sha256-0ei4SOWktanzAX7UuoENy7Cfv1b4s4EKgBl2imSNhXI=";
    };
  };
  awakened-poe-trade-x86_64-linux = {
    pname = "awakened-poe-trade-x86_64-linux";
    version = "3.28.103";
    src = fetchurl {
      url = "https://github.com/SnosMe/awakened-poe-trade/releases/download/v3.28.103/Awakened-PoE-Trade-3.28.103.AppImage";
      sha256 = "sha256-p/XDWnE9lm/LwT3r/lhQWtEJ3YoaGRFd4Rv7RbdDIeg=";
    };
  };
  gemini-cli = {
    pname = "gemini-cli";
    version = "v0.38.2";
    src = fetchurl {
      url = "https://github.com/google-gemini/gemini-cli/releases/download/v0.38.2/gemini-cli-bundle.zip";
      sha256 = "sha256-GcRcTnCHyB/jgYgIQzEU1gAa8dvEbBWKTCvMi7WHyVY=";
    };
  };
  googlesans-code = {
    pname = "googlesans-code";
    version = "v7.000";
    src = fetchurl {
      url = "https://github.com/googlefonts/googlesans-code/releases/download/v7.000/GoogleSansCode-v7.000.zip";
      sha256 = "sha256-W9KUKDy5MXJZi3+k9ihVxjx59VuAPnXXOHd/CTtzxYY=";
    };
  };
  prek = {
    pname = "prek";
    version = "v0.3.10";
    src = fetchurl {
      url = "https://github.com/j178/prek/releases/download/v0.3.10/prek-aarch64-apple-darwin.tar.gz";
      sha256 = "sha256-6IXgI923ZboxooWb1LloP5tA/uMZXBiadJvEsoU1q1w=";
    };
  };
  prek-x86_64-linux = {
    pname = "prek-x86_64-linux";
    version = "v0.3.10";
    src = fetchurl {
      url = "https://github.com/j178/prek/releases/download/v0.3.10/prek-x86_64-unknown-linux-gnu.tar.gz";
      sha256 = "sha256-9+uIQgNuYmBu/0vZhtHzSvJ+2T32mfxz/+nGiYDrB1A=";
    };
  };
  pvetui = {
    pname = "pvetui";
    version = "1.3.2";
    src = fetchurl {
      url = "https://github.com/devnullvoid/pvetui/releases/download/v1.3.2/pvetui_1.3.2_darwin_arm64.tar.gz";
      sha256 = "sha256-+Dqe08N7YS/l4Z/v5c48N03err2McRaYzglkBB1I0Sc=";
    };
  };
  pvetui-x86_64-linux = {
    pname = "pvetui-x86_64-linux";
    version = "1.3.2";
    src = fetchurl {
      url = "https://github.com/devnullvoid/pvetui/releases/download/v1.3.2/pvetui_1.3.2_linux_amd64.tar.gz";
      sha256 = "sha256-U1FKdKn3VMDuE7nYQ/rvmzmVqsaZ+MkymD/K+0W5Hh8=";
    };
  };
  rusty-path-of-building = {
    pname = "rusty-path-of-building";
    version = "v0.2.16";
    src = fetchFromGitHub {
      owner = "meehl";
      repo = "rusty-path-of-building";
      rev = "v0.2.16";
      fetchSubmodules = false;
      sha256 = "sha256-2pXT9Wyn49sGHDqjlmlCRUyIIAEERAKNK6cDTUwwjGM=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-2pXT9Wyn49sGHDqjlmlCRUyIIAEERAKNK6cDTUwwjGM=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  sf-symbols = {
    pname = "sf-symbols";
    version = "7";
    src = fetchurl {
      url = "https://developer.apple.com/download/files/SF-Symbols-7.dmg";
      sha256 = "sha256-pv9A0PBFjLOk/I3i/OhcrOldFIBtYKrQyKi4vbjjy1c=";
    };
  };
  sketchybar-helper = {
    pname = "sketchybar-helper";
    version = "73ee34d377f62fc12ddbf519a2bcdb4b7946292a";
    src = fetchFromGitHub {
      owner = "FelixKratz";
      repo = "SketchyBarHelper";
      rev = "73ee34d377f62fc12ddbf519a2bcdb4b7946292a";
      fetchSubmodules = false;
      sha256 = "sha256-RqL0QkHV6mvPPt7ibdyhMN6vHZGFIw4VkV+kdE4GI5Y=";
    };
  };
  television = {
    pname = "television";
    version = "0.15.6";
    src = fetchFromGitHub {
      owner = "alexpasmantier";
      repo = "television";
      rev = "0.15.6";
      fetchSubmodules = false;
      sha256 = "sha256-0oWgVfybsSLHDeAqTQP2ijJ/84XdcdqD0eqxIv6jk9o=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-0oWgVfybsSLHDeAqTQP2ijJ_84XdcdqD0eqxIv6jk9o=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  worktrunk = {
    pname = "worktrunk";
    version = "v0.44.0";
    src = fetchurl {
      url = "https://github.com/max-sixty/worktrunk/releases/download/v0.44.0/worktrunk-aarch64-apple-darwin.tar.xz";
      sha256 = "sha256-ltv1Ki6Q8dPlS31m76LnBuVtY+NbLqrfrrrPbOAz2BU=";
    };
  };
}
