# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  awakened-poe-trade = {
    pname = "awakened-poe-trade";
    version = "3.28.103";
    src = fetchurl {
      url = "https://github.com/SnosMe/awakened-poe-trade/releases/download/v3.28.103/Awakened-PoE-Trade-3.28.103-universal.dmg";
      sha256 = "sha256-0ei4SOWktanzAX7UuoENy7Cfv1b4s4EKgBl2imSNhXI=";
    };
  };
  awakened-poe-trade-x86_64-linux = {
    pname = "awakened-poe-trade-x86_64-linux";
    version = "3.28.103";
    src = fetchurl {
      url = "https://github.com/SnosMe/awakened-poe-trade/releases/download/v3.28.103/Awakened-PoE-Trade-3.28.103.AppImage";
      sha256 = "sha256-p/XDWnE9lm/LwT3r/lhQWtEJ3YoaGRFd4Rv7RbdDIeg=";
    };
  };
  googlesans-code = {
    pname = "googlesans-code";
    version = "v7.001";
    src = fetchurl {
      url = "https://github.com/googlefonts/googlesans-code/releases/download/v7.001/GoogleSansCode-v7.001.zip";
      sha256 = "sha256-7ruipDiII5boUwytbWy4AYKwr7bp4K0HtzQDWaU7ouk=";
    };
  };
  prek = {
    pname = "prek";
    version = "v0.4.4";
    src = fetchurl {
      url = "https://github.com/j178/prek/releases/download/v0.4.4/prek-aarch64-apple-darwin.tar.gz";
      sha256 = "sha256-09dPlru5/ojRS9sxGVAfjzlgK4heGfV8ZWd5FZmv0jE=";
    };
  };
  prek-x86_64-linux = {
    pname = "prek-x86_64-linux";
    version = "v0.4.4";
    src = fetchurl {
      url = "https://github.com/j178/prek/releases/download/v0.4.4/prek-x86_64-unknown-linux-gnu.tar.gz";
      sha256 = "sha256-5/2pWV2psnvoDYGf1SVjI6+RM+4lFOSyrn66XrxE3pE=";
    };
  };
  pvetui = {
    pname = "pvetui";
    version = "1.4.1";
    src = fetchurl {
      url = "https://github.com/devnullvoid/pvetui/releases/download/v1.4.1/pvetui_1.4.1_darwin_arm64.tar.gz";
      sha256 = "sha256-LohAi62OQb6PB1jQgxx0iifo2EMIrqwPUecMuyxUjIA=";
    };
  };
  pvetui-x86_64-linux = {
    pname = "pvetui-x86_64-linux";
    version = "1.4.1";
    src = fetchurl {
      url = "https://github.com/devnullvoid/pvetui/releases/download/v1.4.1/pvetui_1.4.1_linux_amd64.tar.gz";
      sha256 = "sha256-f4EMDKDk0xa5OxXIfe4NhhRxvQ8WNVHC5mmAmWdkRkw=";
    };
  };
  rusty-path-of-building = {
    pname = "rusty-path-of-building";
    version = "v0.2.18";
    src = fetchFromGitHub {
      owner = "meehl";
      repo = "rusty-path-of-building";
      rev = "v0.2.18";
      fetchSubmodules = false;
      sha256 = "sha256-9YHXTUtTJO3GPf+NqASEkxf+a94doBGTjLyYruuxRg4=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-9YHXTUtTJO3GPf+NqASEkxf+a94doBGTjLyYruuxRg4=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  sf-symbols = {
    pname = "sf-symbols";
    version = "7";
    src = fetchurl {
      url = "https://developer.apple.com/download/files/SF-Symbols-7.dmg";
      sha256 = "sha256-pv9A0PBFjLOk/I3i/OhcrOldFIBtYKrQyKi4vbjjy1c=";
    };
  };
  sketchybar-helper = {
    pname = "sketchybar-helper";
    version = "73ee34d377f62fc12ddbf519a2bcdb4b7946292a";
    src = fetchFromGitHub {
      owner = "FelixKratz";
      repo = "SketchyBarHelper";
      rev = "73ee34d377f62fc12ddbf519a2bcdb4b7946292a";
      fetchSubmodules = false;
      sha256 = "sha256-RqL0QkHV6mvPPt7ibdyhMN6vHZGFIw4VkV+kdE4GI5Y=";
    };
  };
  television = {
    pname = "television";
    version = "0.15.9";
    src = fetchFromGitHub {
      owner = "alexpasmantier";
      repo = "television";
      rev = "0.15.9";
      fetchSubmodules = false;
      sha256 = "sha256-JrQUFlhAAaB+VGP184I44hSsIyfCaTMNXxyPp0E5GM0=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-JrQUFlhAAaB+VGP184I44hSsIyfCaTMNXxyPp0E5GM0=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  worktrunk = {
    pname = "worktrunk";
    version = "v0.58.0";
    src = fetchurl {
      url = "https://github.com/max-sixty/worktrunk/releases/download/v0.58.0/worktrunk-aarch64-apple-darwin.tar.xz";
      sha256 = "sha256-/pywcUvQ5Mq8NFZNWjm60wQOjSpVFA0I4CVk8UrqKWI=";
    };
  };
}
