# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  awakened-poe-trade = {
    pname = "awakened-poe-trade";
    version = "3.28.103";
    src = fetchurl {
      url = "https://github.com/SnosMe/awakened-poe-trade/releases/download/v3.28.103/Awakened-PoE-Trade-3.28.103-universal.dmg";
      sha256 = "sha256-0ei4SOWktanzAX7UuoENy7Cfv1b4s4EKgBl2imSNhXI=";
    };
  };
  awakened-poe-trade-x86_64-linux = {
    pname = "awakened-poe-trade-x86_64-linux";
    version = "3.28.103";
    src = fetchurl {
      url = "https://github.com/SnosMe/awakened-poe-trade/releases/download/v3.28.103/Awakened-PoE-Trade-3.28.103.AppImage";
      sha256 = "sha256-p/XDWnE9lm/LwT3r/lhQWtEJ3YoaGRFd4Rv7RbdDIeg=";
    };
  };
  browserpass = {
    pname = "browserpass";
    version = "3.1.2";
    src = fetchurl {
      url = "https://github.com/browserpass/browserpass-native/releases/download/v3.1.2/browserpass-darwin-arm64-3.1.2.tar.gz";
      sha256 = "sha256-4ZHV3Zf2tYsOgBbsIml52E64bz1z6O8I9zdllviFIGA=";
    };
  };
  browserpass-x86_64-linux = {
    pname = "browserpass-x86_64-linux";
    version = "3.1.2";
    src = fetchurl {
      url = "https://github.com/browserpass/browserpass-native/releases/download/v3.1.2/browserpass-linux64-3.1.2.tar.gz";
      sha256 = "sha256-Ci37oTHetxVTpJ3ZTBanuEiTXpoFXs/Ca21v5cgYnio=";
    };
  };
  googlesans-code = {
    pname = "googlesans-code";
    version = "v7.001";
    src = fetchurl {
      url = "https://github.com/googlefonts/googlesans-code/releases/download/v7.001/GoogleSansCode-v7.001.zip";
      sha256 = "sha256-7ruipDiII5boUwytbWy4AYKwr7bp4K0HtzQDWaU7ouk=";
    };
  };
  miaoyan = {
    pname = "miaoyan";
    version = "4.0.0";
    src = fetchurl {
      url = "https://github.com/tw93/MiaoYan/releases/download/V4.0.0/MiaoYan_V4.0.0.zip";
      sha256 = "sha256-qgWyYLLnZRIKsYqdXT7DQLP54MPwWRJqqzur2IBWou8=";
    };
  };
  mole = {
    pname = "mole";
    version = "1.44.1";
    src = fetchurl {
      url = "https://github.com/tw93/mole/archive/refs/tags/V1.44.1.tar.gz";
      sha256 = "sha256-+lq+UPGQ3li7onM1KSj7roCnIU0HEZN9J5FO33ry2h4=";
    };
  };
  open-super-whisper = {
    pname = "open-super-whisper";
    version = "0.1.0";
    src = fetchurl {
      url = "https://github.com/Starmel/OpenSuperWhisper/releases/download/0.1.0/OpenSuperWhisper.dmg";
      sha256 = "sha256-r1ylFCwi5b7Tun0mQiI8CkgeSZNfWlps8bx2bH7NnWk=";
    };
  };
  prek = {
    pname = "prek";
    version = "v0.4.6";
    src = fetchurl {
      url = "https://github.com/j178/prek/releases/download/v0.4.6/prek-aarch64-apple-darwin.tar.gz";
      sha256 = "sha256-IElbEJzvQfbXGIBB5AyTgqgw/wRwb3wC8wN0qQNSEO8=";
    };
  };
  prek-x86_64-linux = {
    pname = "prek-x86_64-linux";
    version = "v0.4.6";
    src = fetchurl {
      url = "https://github.com/j178/prek/releases/download/v0.4.6/prek-x86_64-unknown-linux-gnu.tar.gz";
      sha256 = "sha256-E1mWNaIgd/Ctbvw16d2qxzzgu54QibS+U8p2tujL8Oc=";
    };
  };
  pvetui = {
    pname = "pvetui";
    version = "1.4.2";
    src = fetchurl {
      url = "https://github.com/devnullvoid/pvetui/releases/download/v1.4.2/pvetui_1.4.2_darwin_arm64.tar.gz";
      sha256 = "sha256-5YTHH7f2lF4ECGJMx0B74wFM9MWGaJGno2V6fxGrhWk=";
    };
  };
  pvetui-x86_64-linux = {
    pname = "pvetui-x86_64-linux";
    version = "1.4.2";
    src = fetchurl {
      url = "https://github.com/devnullvoid/pvetui/releases/download/v1.4.2/pvetui_1.4.2_linux_amd64.tar.gz";
      sha256 = "sha256-vUSZhs8g1MlpPrfDkx7SyIyA/1Xa7R9UnrALm8K3muc=";
    };
  };
  rusty-path-of-building = {
    pname = "rusty-path-of-building";
    version = "v0.2.18";
    src = fetchFromGitHub {
      owner = "meehl";
      repo = "rusty-path-of-building";
      rev = "v0.2.18";
      fetchSubmodules = false;
      sha256 = "sha256-9YHXTUtTJO3GPf+NqASEkxf+a94doBGTjLyYruuxRg4=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-9YHXTUtTJO3GPf+NqASEkxf+a94doBGTjLyYruuxRg4=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  sf-symbols = {
    pname = "sf-symbols";
    version = "7";
    src = fetchurl {
      url = "https://developer.apple.com/download/files/SF-Symbols-7.dmg";
      sha256 = "sha256-pv9A0PBFjLOk/I3i/OhcrOldFIBtYKrQyKi4vbjjy1c=";
    };
  };
  sketchybar-helper = {
    pname = "sketchybar-helper";
    version = "73ee34d377f62fc12ddbf519a2bcdb4b7946292a";
    src = fetchFromGitHub {
      owner = "FelixKratz";
      repo = "SketchyBarHelper";
      rev = "73ee34d377f62fc12ddbf519a2bcdb4b7946292a";
      fetchSubmodules = false;
      sha256 = "sha256-RqL0QkHV6mvPPt7ibdyhMN6vHZGFIw4VkV+kdE4GI5Y=";
    };
  };
  television = {
    pname = "television";
    version = "0.15.9";
    src = fetchFromGitHub {
      owner = "alexpasmantier";
      repo = "television";
      rev = "0.15.9";
      fetchSubmodules = false;
      sha256 = "sha256-JrQUFlhAAaB+VGP184I44hSsIyfCaTMNXxyPp0E5GM0=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-JrQUFlhAAaB+VGP184I44hSsIyfCaTMNXxyPp0E5GM0=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  worktrunk = {
    pname = "worktrunk";
    version = "v0.65.0";
    src = fetchurl {
      url = "https://github.com/max-sixty/worktrunk/releases/download/v0.65.0/worktrunk-aarch64-apple-darwin.tar.xz";
      sha256 = "sha256-X4seMCmoKlIb1XH4ixlkCnNjq5OyFUh6L2dP/Kx3K+k=";
    };
  };
}
